### ISSUE TITLE
Unhandled exception issue in Mac OS .NET

### ISSUE THREAD

**Issue by ahboyJC** [UrmaGurd/UrmaDealGenie#39]
Hi Urma. The process was aborted due to this unhandled exception error. Any advice?

======================
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at UrmaDealGenie.Function.FunctionHandler(DealRuleSet dealRuleSet, ILambdaContext context)
   at DealGenieWorkerService.DoWork(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
zsh: abort

**Comment by UrmaGurd** [comment]
Please DM me on Discord to raise issues, there's not enought information here to go on. I need to know:
- what version you are running
- dealjson configuration
- what files are in your folder
- full log file/output
