### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Razzertaz** [UrmaGurd/UrmaDealGenie#57]
Hi Urma

I got your program running on another computer, when I checked it today it had crashed. It's been running fine for at least half a day up to this. Now I restarted it, and it's running fine again.
It's the UrmaDealGenieApp-win10-x64 version 3.0.

Log:
```
Run Deal Genie...
update = True
Blacklist pairs: BUSD_SHIB, BUSD_USDC, BUSD_UST, BUSD_USDP, BUSD_DOGE, BUSD_BTC, BUSD_ETH, BUSD_SOL, BUSD_ADA, BUSD_CHZ, BUSD_MATIC, BUSD_LTC, BUSD_SLP, BUSD_TLM, BUSD_XRP, BUSD_BNB
Retrieved CoinMarketCap data, top 200 pairs
LunarCrushHelpers.GetApiKey() - Key: <removed>
Retrieved 'Altrank' LunarCrush data, top 100 pairs
==================================================
Bot 8020642 - Processing LunarCrushPairRule 'Altrank' metric, for rule 'Paper Lunar test'
Bot 8020642 - 'Paper test lunar crush' currently has 35 Max Active Deals, and these pairs:
Bot 8020642 -> BUSD_GALA, BUSD_AXS, BUSD_RUNE, BUSD_ZEC, BUSD_SAND, BUSD_ICP, BUSD_NEAR, BUSD_JST, BUSD_THETA, BUSD_MBOX, BUSD_ALICE, BUSD_BCH, BUSD_XLM, BUSD_HNT, BUSD_ZIL, BUSD_CHR, BUSD_MANA, BUSD_STX, BUSD_FLOW, BUSD_HIVE, BUSD_EGLD, BUSD_WAVES, BUSD_ENJ, BUSD_MOVR, BUSD_GLMR, BUSD_SCRT, BUSD_POLY, BUSD_RAY, BUSD_PYR, BUSD_XMR, BUSD_TRX, BUSD_ATOM, BUSD_COMP, BUSD_SYS, BUSD_KAVA
Bot 8020642 - Pair base currency: BUSD
Bot 8020642 - Minimum 24h Volume in BTC: 0
Bot 8020642 - Max Altrank Score for found pairs: 1000
Bot 8020642 - Max CoinMarketCap Rank for found pairs : 200
Bot 8020642 - Found 1427 pairs on 'Paper' mode account 'Paper Account 529857' exchange paper_trading
Bot 8020642 - BTC price on paper_trading exchange $41493,32
Bot 8020642 - looking for 35 pairs in LunarCrush data
Bot 8020642 - replacing 34 best pairs for bot 'Paper test lunar crush':
Bot 8020642 -> BUSD_GALA, BUSD_AXS, BUSD_ZEC, BUSD_RUNE, BUSD_NEAR, BUSD_JST, BUSD_THETA, BUSD_ICP, BUSD_SAND, BUSD_ALICE, BUSD_CHR, BUSD_MBOX, BUSD_BCH, BUSD_XLM, BUSD_HNT, BUSD_ZIL, BUSD_HIVE, BUSD_STX, BUSD_FLOW, BUSD_MANA, BUSD_MOVR, BUSD_WAVES, BUSD_ENJ, BUSD_POLY, BUSD_SCRT, BUSD_PYR, BUSD_GLMR, BUSD_EGLD, BUSD_RAY, BUSD_XMR, BUSD_TRX, BUSD_KAVA, BUSD_SYS, BUSD_NU
{
  "BotPairResponses": [
    {
      "Rule": "Paper Lunar test",
      "PairCount": 34,
      "Updated": true
    }
  ],
  "DealResponses": []
}
Deal Genie completed
Run Deal Genie...
update = True
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UrmaDealGenie.LunarCrushPairRuleProcessor.GetBlacklist()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at UrmaDealGenie.LunarCrushPairRuleProcessor.ProcessRules(List`1 dealRuleSet, Boolean update)
   at UrmaDealGenie.Urma3cClient.ProcessRules(DealRuleSet dealRuleSet)
   at DealGenieWorkerService.DoWork(Object state)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by UrmaGurd** [comment]
Please DM me as per the instruction you saw before raising this issue
